### ISSUE TITLE
Complete API

### ISSUE THREAD

**Issue by alecello** [WEEE-Open/Sneck#1]
Check that all data that the API provides across all endpoints is part of the class tree in **Deck.py**.
The [NextCloud Deck API documentation](https://deck.readthedocs.io/en/latest/API/) can be used as a reference.

- Each element should be private and have a getter method to retrieve it.
- Naming for API functions should be consistent: this needs to be checked before the API reaches production sate.

**Comment by kuzeykara** [comment]
I compared the Nextcloud Deck API documentation with the code and made sure that all the data (apart from displayname and primaryKey of users) is stored and has getters
